# SPDX-License-Identifier: BSD-3-Clause
"""Generate the Nostr-host profile vectors in ../../vectors/profiles/.

Illustrative EvidenceRecord fixtures for the ``nostr-pubkey`` host-principal profile and the
three Evidence Contract profiles for Nostr-based agent hosts. Two namings are emitted from the
same builders:

- ``nostr-host.{agent-job,moderation,release}/v1`` (current): neutral ids, ``host.example``
  hosts, ``host-*`` key and source ids.
- ``buzz.{agent-job,moderation,release}/v1``: released in 0.6.0, superseded by the set above,
  kept as released bytes. They are FROZEN: the generator must keep reproducing them exactly.

Every record carries the one uniform subject shape ``subject: {event_id, semantic_digest}``;
any further digested fact is a NAMED body digest in ``payload_commitments`` (``role`` names the
fact), never a second subject field.

Every 64-hex value is ``json_digest({"label": <label>})`` over a labelled placeholder, and each
fixture lists its ``digest_labels`` so the Go and TypeScript parity tests re-derive every value
from the same label and assert the same committed files. Each fixture also carries ``expect``:
the rule codes :func:`check_record` must report (empty for a positive).

The rule set is deliberately small and identical in all three languages:

- ``subject_shape``          subject is exactly ``{event_id, semantic_digest}``, both 64-hex.
- ``event_id_as_digest``     the transport event id is reused as a digest (subject or body).
- ``body_digest_named``      every body digest names its fact; none reuses ``semantic_digest``.
- ``message_text_present``   a field whose name marks free text (text/message/content/body).
- ``score_present``          a field whose name marks a score/rating/rank.

Run: cd python && python -m scripts.generate_profile_vectors
"""
from __future__ import annotations

import copy
import json
import re
from pathlib import Path
from typing import Any, NamedTuple

from agent_action_capsule.canonical import json_digest

OUT = Path(__file__).resolve().parents[2] / "vectors" / "profiles"

HEX64 = re.compile(r"^[0-9a-f]{64}$")
TEXT_KEY = re.compile(r"(^|_)(text|message|content|body)(_|$)")
SCORE_KEY = re.compile(r"(^|_)(score|rating|rank)(_|$)")
RULES = (
    "subject_shape",
    "event_id_as_digest",
    "body_digest_named",
    "message_text_present",
    "score_present",
)

STATUS = (
    "Subject shape ruled 2026-09-23 (uniform `semantic_digest`). Illustrative vector generated by "
    "python/scripts/generate_profile_vectors.py; registry placement is still unruled. See "
    "vectors/profiles/README.md."
)


class Variant(NamedTuple):
    """One naming of the three profiles. Only names differ; construction and rules are shared."""

    prefix: str  # profile-id prefix: "<prefix>.agent-job/v1"
    label_prefix: str  # first segment of every digest label
    ns: str  # subject_ref / actor_role_ref namespace
    ids: str  # prefix of key, model, calibration and policy ids
    relay: str  # principal_ref_relay_hint


#: Released in 0.6.0. FROZEN: these bytes are never rewritten; the generator must keep
#: reproducing them exactly (python/tests/test_profile_vectors.py asserts it).
BUZZ = Variant(
    prefix="buzz",
    label_prefix="buzz-profile-vector",
    ns="buzz",
    ids="buzz",
    relay="wss://relay.buzz.example",
)

#: Current. Neutral copies of the released set: same construction, neutral ids and hosts.
NOSTR_HOST = Variant(
    prefix="nostr-host",
    label_prefix="nostr-host-profile-vector",
    ns="host",
    ids="host",
    relay="wss://relay.host.example",
)

VARIANTS = (NOSTR_HOST, BUZZ)


def label(v: Variant, kind: str, item: str) -> str:
    return f"{v.label_prefix}:{kind}:{item}"


def digest(lbl: str) -> str:
    return json_digest({"label": lbl})


# ---------------------------------------------------------------------------------------------
# Rule checker (mirrored in go/canonical/profile_vectors_test.go and ts/test/profile-vectors.test.ts)


def _walk_keys(value: Any, path: str = "") -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    if isinstance(value, dict):
        for key in sorted(value):
            child = f"{path}.{key}" if path else key
            out.append((key, child))
            out.extend(_walk_keys(value[key], child))
    elif isinstance(value, list):
        for i, item in enumerate(value):
            out.extend(_walk_keys(item, f"{path}.{i}"))
    return out


def check_record(record: dict[str, Any], disabled: frozenset[str] = frozenset()) -> list[str]:
    """Return the sorted rule codes ``record`` violates, skipping any rule in ``disabled``."""
    found: set[str] = set()
    subject = record.get("subject")
    event_id = None
    if not (
        isinstance(subject, dict)
        and set(subject) == {"event_id", "semantic_digest"}
        and all(isinstance(subject[k], str) and HEX64.match(subject[k]) for k in subject)
    ):
        found.add("subject_shape")
    else:
        event_id = subject["event_id"]
    commitments = record.get("payload_commitments", [])
    body_digests = [c.get("digest") for c in commitments if isinstance(c, dict)]
    if event_id is not None and (
        subject["semantic_digest"] == event_id or event_id in body_digests
    ):
        found.add("event_id_as_digest")
    for c in commitments:
        role = c.get("role") if isinstance(c, dict) else None
        if not isinstance(role, str) or not role or role == "semantic_digest":
            found.add("body_digest_named")
    for key, _ in _walk_keys(record):
        if TEXT_KEY.search(key):
            found.add("message_text_present")
        if SCORE_KEY.search(key):
            found.add("score_present")
    return sorted(found - disabled)


# ---------------------------------------------------------------------------------------------
# Fixture builders

def _pubkey_label(v: Variant) -> str:
    return label(v, "nostr-pubkey:principal", f"{v.ids}-agent-key-01")


def _header(
    v: Variant,
    *,
    seq: int,
    record_label: str,
    record_type: str,
    epistemic_type: str,
    subject_ref: str,
    profile: str,
    requirement_refs: list[str],
    event_time: str,
    committed: str,
    event_label: str,
    semantic_label: str,
) -> tuple[dict[str, Any], list[dict[str, str]]]:
    record: dict[str, Any] = {
        "seq": seq,
        "record_id": digest(record_label),
        "record_type": record_type,
        "epistemic_type": epistemic_type,
        "principal_ref": "nostr-pubkey:" + digest(_pubkey_label(v)),
        "principal_ref_relay_hint": v.relay,
        "subject_ref": subject_ref,
        "contract_ref": f"ec:{profile}@1",
        "requirement_refs": requirement_refs,
        "event_time_claim": event_time,
        "committed_at": committed,
        "subject": {
            "event_id": digest(event_label),
            "semantic_digest": digest(semantic_label),
        },
    }
    labels = [
        {"path": "record_id", "label": record_label},
        {"path": "principal_ref", "prefix": "nostr-pubkey:", "label": _pubkey_label(v)},
        {"path": "subject.event_id", "label": event_label},
        {"path": "subject.semantic_digest", "label": semantic_label},
    ]
    return record, labels


def _commit(role: str, lbl: str) -> dict[str, str]:
    return {"digest_alg": "SHA-256", "digest": digest(lbl), "role": role}


def _tail(record: dict[str, Any]) -> dict[str, Any]:
    record["assurance_properties"] = ["self_attested"]
    record["retention_state"] = "AVAILABLE"
    return record


def agent_job(v: Variant) -> tuple[dict[str, Any], list[dict[str, str]]]:
    job = "job-2026-09-22-0001"
    p = f"{v.prefix}.agent-job/v1"
    record, labels = _header(
        v,
        seq=1,
        record_label=label(v, f"{p}:record", job),
        record_type="observation",
        epistemic_type="system_of_record_fact",
        subject_ref=f"{v.ns}:agent-job:{job}",
        profile=p,
        requirement_refs=["req-outcome-1"],
        event_time="2026-09-22T14:03:11Z",
        committed="2026-09-22T14:03:12Z",
        event_label=label(v, f"{p}:nostr-event-id", job),
        semantic_label=label(v, f"{p}:job-outcome-payload", job),
    )
    return _tail(record), labels


MOD = "mod-2026-09-22-0007"


def _mod(v: Variant) -> tuple[str, str, str]:
    """(profile id, event label, semantic label) shared by the three moderation records."""
    p = f"{v.prefix}.moderation/v1"
    return (
        p,
        label(v, f"{p}:nostr-event-id", MOD),
        label(v, f"{p}:moderation-action-payload", MOD),
    )


def moderation_judgment(v: Variant) -> tuple[dict[str, Any], list[dict[str, str]]]:
    p, mod_event, mod_semantic = _mod(v)
    record, labels = _header(
        v,
        seq=10,
        record_label=label(v, f"{p}:semantic-judgment-record", MOD),
        record_type="judgment",
        epistemic_type="semantic_judgment",
        subject_ref=f"{v.ns}:moderation-action:{MOD}",
        profile=p,
        requirement_refs=["req-human-role-1"],
        event_time="2026-09-22T15:10:00Z",
        committed="2026-09-22T15:10:02Z",
        event_label=mod_event,
        semantic_label=mod_semantic,
    )
    content = label(v, f"{p}:moderated-content", MOD)
    decision = label(v, f"{p}:moderation-decision", MOD)
    record["payload_commitments"] = [
        _commit("moderated-content", content),
        _commit("moderation-decision", decision),
    ]
    labels += [
        {"path": "payload_commitments.0.digest", "label": content},
        {"path": "payload_commitments.1.digest", "label": decision},
    ]
    record["judgment"] = {
        "disposition": "removed",
        "evaluator_model_ref": f"{v.ids}-mod-model-v1",
        "calibration_ref": f"{v.ids}-mod-calibration-2026-09",
    }
    return _tail(record), labels


def moderation_review(v: Variant) -> tuple[dict[str, Any], list[dict[str, str]]]:
    p, mod_event, mod_semantic = _mod(v)
    record, labels = _header(
        v,
        seq=11,
        record_label=label(v, f"{p}:human-report-review-record", MOD),
        record_type="human_report",
        epistemic_type="human_report",
        subject_ref=f"{v.ns}:moderation-action:{MOD}",
        profile=p,
        requirement_refs=["req-human-role-2"],
        event_time="2026-09-22T15:20:00Z",
        committed="2026-09-22T15:20:03Z",
        event_label=mod_event,
        semantic_label=mod_semantic,
    )
    record["actor_role_ref"] = f"{v.ns}:moderator"
    record["review"] = {
        "outcome": "confirmed",
        "review_event_ref": f"{v.ns}:moderator-review:{MOD}",
    }
    return _tail(record), labels


def moderation_obligation(v: Variant) -> tuple[dict[str, Any], list[dict[str, str]]]:
    p, mod_event, mod_semantic = _mod(v)
    record, labels = _header(
        v,
        seq=12,
        record_label=label(v, f"{p}:obligation-reference-record", MOD),
        record_type="claim",
        epistemic_type="obligation_reference",
        subject_ref=f"{v.ns}:moderation-action:{MOD}",
        profile=p,
        requirement_refs=["req-obligation-1"],
        event_time="2026-09-22T15:25:00Z",
        committed="2026-09-22T15:25:04Z",
        event_label=mod_event,
        semantic_label=mod_semantic,
    )
    record["obligation_refs"] = ["dsa:article-17", "dsa:article-24-5"]
    return _tail(record), labels


def release(v: Variant) -> tuple[dict[str, Any], list[dict[str, str]]]:
    rel = "release-2026-09-22-0003"
    p = f"{v.prefix}.release/v1"
    record, labels = _header(
        v,
        seq=1,
        record_label=label(v, f"{p}:record", rel),
        record_type="observation",
        epistemic_type="system_of_record_fact",
        subject_ref=f"{v.ns}:release:{rel}",
        profile=p,
        requirement_refs=["req-process-1", "req-obligation-1"],
        event_time="2026-09-22T18:00:00Z",
        committed="2026-09-22T18:00:05Z",
        event_label=label(v, f"{p}:nostr-event-id", rel),
        semantic_label=label(v, f"{p}:release-gate-record", rel),
    )
    approval = label(v, f"{p}:approval-record", rel)
    record["payload_commitments"] = [_commit("approval-record", approval)]
    labels.append({"path": "payload_commitments.0.digest", "label": approval})
    record["obligation_refs"] = [f"{v.ids}-release-policy/section-2/v1"]
    return _tail(record), labels


def _event_id_as_digest(
    base: tuple[dict[str, Any], list[dict[str, str]]],
) -> tuple[dict[str, Any], list[dict[str, str]]]:
    record, labels = copy.deepcopy(base)
    record["subject"]["semantic_digest"] = record["subject"]["event_id"]
    event_label = next(x["label"] for x in labels if x["path"] == "subject.event_id")
    for x in labels:
        if x["path"] == "subject.semantic_digest":
            x["label"] = event_label
    return record, labels


def _with_judgment_field(
    base: tuple[dict[str, Any], list[dict[str, str]]], key: str, value: Any
) -> tuple[dict[str, Any], list[dict[str, str]]]:
    record, labels = copy.deepcopy(base)
    record["judgment"][key] = value
    return record, labels


def cases(v: Variant) -> list[dict[str, Any]]:
    job = agent_job(v)
    mod = moderation_judgment(v)
    rel = release(v)
    p = v.prefix
    out: list[dict[str, Any]] = [
        {
            "file": f"{p}.agent-job/v1/positive-01.json",
            "built": job,
            "expect": [],
            "note": "Agent-job terminal outcome: the uniform subject only; no extra body digest.",
        },
        {
            "file": f"{p}.agent-job/v1/negative-event-id-as-digest.json",
            "built": _event_id_as_digest(job),
            "expect": ["event_id_as_digest"],
            "note": "Mutated from positive-01.json: subject.semantic_digest set equal to "
            "subject.event_id - the transport event id stands in for the semantic digest.",
        },
        {
            "file": f"{p}.moderation/v1/positive-semantic-judgment.json",
            "built": mod,
            "expect": [],
            "note": "Worked content-vs-decision vector: subject.{event_id, semantic_digest} "
            "identify the moderation action event; the moderated content and the decision are "
            "two NAMED body digests (payload_commitments roles moderated-content and "
            "moderation-decision), never subject fields. One of the three records whose "
            f"combination a {p}.moderation/v1 requirement needs.",
        },
        {
            "file": f"{p}.moderation/v1/positive-human-report-review.json",
            "built": moderation_review(v),
            "expect": [],
            "note": "A human moderator's own review over the same moderation action (same "
            "subject). One of the three records whose combination is required.",
        },
        {
            "file": f"{p}.moderation/v1/positive-obligation-reference.json",
            "built": moderation_obligation(v),
            "expect": [],
            "note": "Cites DSA Art. 17 and Art. 24(5) for the same moderation action; a "
            "citation, never a compliance conclusion. One of the three records whose "
            "combination is required.",
        },
        {
            "file": f"{p}.moderation/v1/negative-event-id-as-digest.json",
            "built": _event_id_as_digest(mod),
            "expect": ["event_id_as_digest"],
            "note": "Mutated from positive-semantic-judgment.json: subject.semantic_digest set "
            "equal to subject.event_id.",
        },
        {
            "file": f"{p}.moderation/v1/negative-message-text-present.json",
            "built": _with_judgment_field(
                mod, "moderated_text", "example moderated message text carried inline"
            ),
            "expect": ["message_text_present"],
            "note": "Mutated from positive-semantic-judgment.json: judgment.moderated_text "
            "carries free text inline. Records carry digests only, never message text.",
        },
        {
            "file": f"{p}.moderation/v1/negative-score-field-present.json",
            "built": _with_judgment_field(mod, "principal_trust_score", 42),
            "expect": ["score_present"],
            "note": "Mutated from positive-semantic-judgment.json: judgment.principal_trust_score "
            "carries a numeric score. No field carries a score or per-user history.",
        },
        {
            "file": f"{p}.release/v1/positive-01.json",
            "built": rel,
            "expect": [],
            "note": "Release gate: the uniform subject identifies the release-gate record; the "
            "separate approval record is a NAMED body digest (role approval-record).",
        },
        {
            "file": f"{p}.release/v1/negative-event-id-as-digest.json",
            "built": _event_id_as_digest(rel),
            "expect": ["event_id_as_digest"],
            "note": "Mutated from positive-01.json: subject.semantic_digest set equal to "
            "subject.event_id.",
        },
    ]
    return out


def render() -> dict[str, str]:
    """Return {relative path: file text} for every generated file."""
    files: dict[str, str] = {}
    manifest = []
    for case in (c for v in VARIANTS for c in cases(v)):
        record, labels = case["built"]
        got = check_record(record)
        if got != case["expect"]:
            raise AssertionError(f"{case['file']}: rules {got} != expected {case['expect']}")
        doc = {
            "_status": STATUS,
            "_note": case["note"],
            "expect": {"valid": not case["expect"], "violations": case["expect"]},
            "digest_labels": labels,
            "record": record,
        }
        files[case["file"]] = json.dumps(doc, indent=2, ensure_ascii=False) + "\n"
        manifest.append(
            {"file": case["file"], "valid": not case["expect"], "violations": case["expect"]}
        )
    files["manifest.json"] = (
        json.dumps(
            {
                "generator": "python/scripts/generate_profile_vectors.py",
                "label_digest": 'json_digest({"label": <label>})',
                "rules": list(RULES),
                "cases": manifest,
            },
            indent=2,
        )
        + "\n"
    )
    return files


def main() -> None:
    for rel, text in render().items():
        path = OUT / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
