// SPDX-License-Identifier: BSD-3-Clause
package registries

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestLoadAuthoritative(t *testing.T) {
	known, err := LoadAuthoritative()
	require.NoError(t, err)
	assert.True(t, known["effect.type"]["write_order"])
	assert.True(t, known["citation_purpose"]["responds_to"])
}

func TestEmbeddedAuthoritativeRegistryMatchesSpec(t *testing.T) {
	expected, err := os.ReadFile("../../spec/REGISTRY.md")
	if os.IsNotExist(err) {
		t.Skip("spec/REGISTRY.md is unavailable outside the source checkout")
	}
	require.NoError(t, err)
	assert.Equal(t, expected, authoritativeRegistry, "run go generate ./registries after changing spec/REGISTRY.md")
}

// registriesDoc is the shape of registries.json.
type registriesDoc struct {
	Source      string           `json:"source"`
	GeneratedBy string           `json:"generated_by"`
	Registries  map[string]Table `json:"registries"`
}

func TestEmbeddedJSONMatchesGoParse(t *testing.T) {
	// Parity: registries.json is generated by the Python parser; the Go parser
	// must read the same embedded REGISTRY.md to the same tables.
	var doc registriesDoc
	require.NoError(t, json.Unmarshal(registriesJSON, &doc))
	tables, err := ParseTables(bytes.NewReader(authoritativeRegistry))
	require.NoError(t, err)
	require.Len(t, doc.Registries, len(tables))
	for _, tbl := range tables {
		want, ok := doc.Registries[tbl.Name]
		require.True(t, ok, tbl.Name)
		want.Name = tbl.Name
		assert.Equal(t, want, tbl, tbl.Name)
	}
	// Document order is preserved in the JSON object.
	dec := json.NewDecoder(bytes.NewReader(registriesJSON))
	var keys []string
	depth := 0
	for {
		tok, err := dec.Token()
		if err != nil {
			break
		}
		switch v := tok.(type) {
		case json.Delim:
			if v == '{' || v == '[' {
				depth++
			} else {
				depth--
			}
		case string:
			if depth == 2 && dec.More() {
				keys = append(keys, v)
				var skip json.RawMessage
				require.NoError(t, dec.Decode(&skip))
			}
		}
	}
	assert.Equal(t, AllRegistryNames, keys)
}

func TestEmbeddedJSONMatchesPythonCopy(t *testing.T) {
	expected, err := os.ReadFile("../../python/agent_action_capsule/data/registries.json")
	if os.IsNotExist(err) {
		t.Skip("python/ is unavailable outside the source checkout")
	}
	require.NoError(t, err)
	assert.Equal(t, expected, registriesJSON, "run go generate ./registries after regenerating registries.json")
	assert.Equal(t, registriesJSON, JSON())
}

func TestEveryRegistryParsed(t *testing.T) {
	tables, err := ParseTables(bytes.NewReader(authoritativeRegistry))
	require.NoError(t, err)
	names := make([]string, 0, len(tables))
	sections := make(map[string]bool)
	for _, tbl := range tables {
		names = append(names, tbl.Name)
		sections[tbl.Section] = true
		assert.NotEmpty(t, tbl.Values, tbl.Name)
	}
	assert.Equal(t, AllRegistryNames, names)
	assert.Len(t, sections, 18)
	known, err := LoadAuthoritative()
	require.NoError(t, err)
	assert.Len(t, known, len(AllRegistryNames))
}

func TestNamedAccessors(t *testing.T) {
	assert.Equal(t, []string{
		"observed_event", "system_of_record_fact", "producer_claim", "human_report",
		"semantic_judgment", "derived_metric", "adjudication", "obligation_reference",
	}, EpistemicTypes())
	assert.Equal(t, []string{"cites", "adjudicates", "supersedes", "acknowledges", "rebuts", "closes"}, LinkTypes())
	assert.Equal(t, []string{"follows", "confirms", "supersedes", "epoch_opens", "duplicates"}, ChainRelations())
	assert.Equal(t, []string{
		"acted_on", "responds_to", "ran_under", "corroborates_source_time",
		"counterparty_half", "counterparty_inclusion",
	}, CitationPurposes())
	_, err := Values("no_such_registry")
	assert.Error(t, err)
	fields, err := Values("disclosure_envelope.disclosable_field")
	require.NoError(t, err)
	assert.Len(t, fields, len(DisclosureEligibleFields))
	for _, f := range fields {
		assert.Contains(t, DisclosureEligibleFields, f)
	}
}

func TestProvisionalSubsectionsNotSeeded(t *testing.T) {
	exts, err := Values("evidence_bundle.extension_kind")
	require.NoError(t, err)
	assert.NotContains(t, exts, "disclosure-policy-decisions/v1")
	assert.NotContains(t, exts, "sd-jwt-issuers/v1")
	derivs, err := Values("evidence_request.derivation")
	require.NoError(t, err)
	assert.Equal(t, []string{"history_card/1"}, derivs)
}

const preCitationPurpose = "## 1. `verdict_class`\n\n| Value | Semantics |\n|---|---|\n| `executed` | ran |\n\n" +
	"## 2. `disposition.decision`\nInitial contents: `accept`, `reject`.\n\n" +
	"## 3. `effect.type`\nInitial contents: `write_order`.\n\n" +
	"## 4. `irreversibility_class`\n\n1. `two_way`\n\n" +
	"## 5. `effect_attestation`\n\n| Value | Semantics |\n|---|---|\n| `gate_executed` | observed |\n\n" +
	"## 6. `chain.relation`\n\n| Value | Semantics |\n|---|---|\n| `confirms` | non-terminal |\n\n## No registry\n"

// Regression: an older snapshot that predates citation_purpose used to load it
// as an empty set; it is now absent, so callers can tell the two apart.
func TestOlderSnapshotOmitsCitationPurpose(t *testing.T) {
	path := filepath.Join(t.TempDir(), "REGISTRY.md")
	require.NoError(t, os.WriteFile(path, []byte(preCitationPurpose), 0o644))
	known, err := Load(path)
	require.NoError(t, err)
	_, has := known["citation_purpose"]
	assert.False(t, has)
	_, has = known["epistemic_type"]
	assert.False(t, has)
	assert.True(t, known["chain.relation"]["confirms"])
}

func TestOlderSnapshotRequiresCoreRegistries(t *testing.T) {
	path := filepath.Join(t.TempDir(), "REGISTRY.md")
	broken := strings.Replace(preCitationPurpose, "1. `two_way`", "Prose only.", 1)
	require.NoError(t, os.WriteFile(path, []byte(broken), 0o644))
	_, err := Load(path)
	assert.ErrorContains(t, err, "irreversibility_class")
}

func TestEmptyNonCoreRegistryIsEmptyNotAbsent(t *testing.T) {
	tables, err := ParseTables(strings.NewReader("## 14. Evidence Bundle extension kind\n\nNo initial extension kind is defined.\n"))
	require.NoError(t, err)
	require.Len(t, tables, 1)
	assert.Equal(t, "evidence_bundle.extension_kind", tables[0].Name)
	assert.Empty(t, tables[0].Values)
}
