import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { bundleDigest, verifyBundle } from "../src/bundle.js";
import {
  classifyCountersignatures,
  declaredProducerKeys,
  PRODUCER_KEY_V1,
  type CountersignatureStamp,
} from "../src/countersignature-stamp.js";
import { jcs } from "../src/json.js";
import { derivedFixture } from "./helpers/derived-fixtures.js";

// The Evidence Bundle -01 producer-key/v1 vectors
// (vectors/bundle/producer-key, generated by
// python/scripts/generate_bundle_producer_key_vectors.py).
const DIR = resolve(process.cwd(), "..", "vectors", "bundle", "producer-key");

type Case = {
  id: string;
  bundle: Record<string, unknown>;
  bundle_digest: string;
  expect: {
    signature: "valid";
    declared_producer_keys: string[];
    stamp: "not independent" | "unresolved signer";
  };
};

const raw = readFileSync(resolve(DIR, "vectors.json"));
const corpus = JSON.parse(raw.toString("utf8")) as {
  extension_block_jcs: string;
  keys: { producer_public_key_hex: string };
  cases: Case[];
};

// The draft's state names, as the stamp's kinds spell them.
const STAMP_KIND: Record<
  Case["expect"]["stamp"],
  CountersignatureStamp["kind"]
> = {
  "not independent": "not-independent",
  "unresolved signer": "unresolved-signer",
};

const decode = (bytes: Uint8Array): string => new TextDecoder().decode(bytes);

describe("producer-key/v1 vectors", () => {
  it("vectors.json is the file SHA256SUMS pins", () => {
    const sums = readFileSync(resolve(DIR, "SHA256SUMS"), "utf8");
    const digest = createHash("sha256").update(raw).digest("hex");
    expect(sums).toContain(`${digest}  vectors.json`);
  });

  it("the extension block is byte-identical to capsulectl's and the derived fixture's", async () => {
    const producer = corpus.keys.producer_public_key_hex;
    // capsulectl (capsule-cli internal/cli producer_key_test.go) asserts this JCS form.
    expect(corpus.extension_block_jcs).toBe(
      `{"producer-key/v1":{"public_key":"${producer}"}}`,
    );
    const declared = corpus.cases.find(
      (c) => c.id === "declared-self-countersignature",
    )!;
    expect(decode(jcs(declared.bundle.extensions))).toBe(
      corpus.extension_block_jcs,
    );
    // The AAC derived fixture uses the same test seed, so the block is the same bytes.
    const fixture = await derivedFixture(
      "week-bundle-producer-countersigned.json",
    );
    expect(decode(jcs(fixture.extensions))).toBe(corpus.extension_block_jcs);
  });

  for (const c of corpus.cases) {
    it(`${c.id}: ${c.expect.stamp}`, async () => {
      const digest = await bundleDigest(c.bundle);
      expect(digest).toBe(c.bundle_digest);
      const keys = declaredProducerKeys(c.bundle);
      expect(keys).toEqual(c.expect.declared_producer_keys);
      const stamps = await classifyCountersignatures(
        c.bundle.countersignatures as unknown[],
        digest,
        keys,
        undefined,
      );
      expect(stamps.map((s) => s.kind)).toEqual([STAMP_KIND[c.expect.stamp]]);

      // Digest-covered and never a failure: the core reports the block as
      // an uninterpreted extension.
      if (c.bundle.extensions !== undefined) {
        const verified = await verifyBundle(c.bundle);
        expect(verified.extensions).toEqual([
          {
            kind: PRODUCER_KEY_V1,
            status: "uninterpreted",
            integrityCovered: true,
          },
        ]);
      }
    });
  }

  it("removing the declaration after signing invalidates the entry, never upgrades it", async () => {
    const c = corpus.cases.find(
      (x) => x.id === "declared-self-countersignature",
    )!;
    const { extensions: _dropped, ...stripped } = c.bundle;
    const stamps = await classifyCountersignatures(
      c.bundle.countersignatures as unknown[],
      await bundleDigest(stripped),
      declaredProducerKeys(stripped),
      undefined,
    );
    expect(stamps.map((s) => s.kind)).toEqual(["invalid"]);
  });
});
