#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""
check_released_vectors.py

Released vectors are never rewritten. vectors/released/<version>/ holds the
exact bytes of fixtures that shipped in a release tag and were later renamed
or regenerated on main, mirrored under their original repository-relative
paths. This check keeps those bytes fixed:

  1. MANIFEST PINNED: each version's SHA256SUMS hashes to the digest pinned in
     RELEASED below, so a file and its SHA256SUMS line cannot be edited
     together without also editing this script.
  2. BYTES PINNED: every file SHA256SUMS lists exists and matches its digest.
  3. CLOSED SET: no file sits in the version directory that SHA256SUMS does not
     list (README.md and SHA256SUMS itself excepted).

These files are NOT current fixtures. No schema checker, generator or vector
runner reads them, and they may fail the current schemas by design (a later
rename or schema change is why they were frozen). They are kept so a consumer
that pinned a release can still find the bytes it pinned.

Usage:
    python3 schemas/check_released_vectors.py       # from repo root

Exit 0: every check passed. Exit 1: a finding was printed. Exit 2: a missing
version directory or manifest.
"""
from __future__ import annotations

import hashlib
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RELEASED_DIR = ROOT / "vectors" / "released"

# version -> sha256 of that version's SHA256SUMS file.
RELEASED = {
    # v0.6.0 / go/v0.6.0 (13a1f45): bytes renamed or regenerated by the
    # EXAMPLE-ORG placeholder rename (#158, 6e7deff).
    "0.6.0": "4236deb5e442d86a48aef7ad5fa4ffc36336d67921377c140bc807a11a504014",
}

UNLISTED_OK = {"README.md", "SHA256SUMS"}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    findings: list[str] = []
    for version, manifest_sha in RELEASED.items():
        base = RELEASED_DIR / version
        sums = base / "SHA256SUMS"
        if not sums.is_file():
            print(f"HARNESS: {sums} not found", file=sys.stderr)
            return 2
        actual = _sha256(sums)
        if actual != manifest_sha:
            findings.append(f"MANIFEST-CHANGED {version}: SHA256SUMS sha256 {actual}, pinned {manifest_sha}")
        listed: set[str] = set()
        for line in sums.read_text(encoding="utf-8").splitlines():
            digest, rel = line.split("  ", 1)
            listed.add(rel)
            path = base / rel
            if not path.is_file():
                findings.append(f"MISSING {version}/{rel}")
                continue
            got = _sha256(path)
            if got != digest:
                findings.append(f"BYTES-CHANGED {version}/{rel}: sha256 {got}, pinned {digest}")
        on_disk = {p.relative_to(base).as_posix() for p in base.rglob("*") if p.is_file()}
        for extra in sorted(on_disk - listed - UNLISTED_OK):
            findings.append(f"UNLISTED {version}/{extra}: not in SHA256SUMS")
        if not findings:
            print(f"OK  released {version}: {len(listed)} file(s), bytes and manifest pinned")
    for f in findings:
        print(f, file=sys.stderr)
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main())
